version: '3.9'
services:
  postgres:
    build: ./postgres/
    container_name: postgres
    image: postgres:16.0-alpine3.18
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  pgAdmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always
  
  redis:
    image: redis:7.2.1-alpine3.18
    restart: always
    ports:
      - '6378:6379'
    volumes:
      - redis:/data

volumes:
  postgres_data: {}
  redis:
    driver: local